// Host-authoritative WebRTC rooms. No game state is accepted from a guest.
let localId=0,roster=[null,null,null,null],peer=null,hostConn=null,isHost=false,room='',epoch=0,seq=0,netTick=0,connections=new Map(),inputs=new Map(),session=0,connectionTimer=null,lastSnapshot=0;
const names=['Red','Violet','Mint','Amber'],PREFIX='skyball-sprint-v1-';
const statusLine=text=>$('netStatus').textContent=text;
const localInput=()=>$('lobby').classList.contains('hidden')?({x:clamp((keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0)+joystick.x,-1,1),y:clamp((keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0)+joystick.y,-1,1)}):({x:0,y:0});
function send(c,data){if(c?.open&&(!c.dataChannel||c.dataChannel.bufferedAmount<65536))c.send(data)}
function broadcast(data){for(const c of connections.values())send(c,data)}
function party(){ $('entry').classList.toggle('hidden',!!room);$('party').classList.toggle('hidden',!room);$('roomCode').textContent=room;$('members').replaceChildren(...roster.map((p,i)=>{const e=document.createElement('div');e.textContent=p?`${names[i]}${i===localId?' · You':''}${i===0?' · Host':''}`:'Waiting for player…';e.style.color=p?'#183049':'#99aab5';return e}));$('invite').value=location.origin+location.pathname+'?room='+room;$('startMatch').classList.toggle('hidden',!isHost||state==='playing');$('startMatch').disabled=roster.filter(Boolean).length<2;$('closeRoom').classList.toggle('hidden',state!=='playing'); }
function clearControls(){keys={};joystick={x:0,y:0};dragControl=null;inputs.clear()}
function leave(message='Create a room or join a friend. 2–4 players.'){session++;clearTimeout(connectionTimer);if(peer)peer.destroy();peer=null;hostConn=null;connections.clear();room='';isHost=false;localId=0;roster=[null,null,null,null];state='lobby';clearControls();stopSounds();$('overlay').classList.add('hidden');$('lobby').classList.remove('hidden');$('createRoom').disabled=$('joinRoom').disabled=false;party();statusLine(message)}
function openRoom(host,code){leave();const generation=session;isHost=host;room=code;state='lobby';statusLine(host?'Creating room…':'Connecting…');$('createRoom').disabled=$('joinRoom').disabled=true;peer=new Peer(host?PREFIX+code:undefined,{debug:0});connectionTimer=setTimeout(()=>{if(generation===session)leave('Connection timed out. Check the code, keep the host open, or try another network.')},20000);
peer.on('error',e=>{if(generation!==session)return;if(e.type==='unavailable-id'||!hostConn&&!isHost||!roster[0])leave('Unable to connect: '+e.type+'. Please try again.');else statusLine('Connection issue: '+e.type)});
peer.on('disconnected',()=>{if(generation===session&&peer&&!peer.destroyed)peer.reconnect()});
peer.on('open',()=>{if(generation!==session)return;if(host){clearTimeout(connectionTimer);roster[0]=true;party();statusLine('Share the invite link. Start when everyone has joined.')}else{hostConn=peer.connect(PREFIX+code,{reliable:true,serialization:'json'});hostConn.on('data',data=>{if(generation===session)receiveHost(data)});hostConn.on('close',()=>{if(generation===session)leave('The host left. Create or join another room.')});hostConn.on('error',()=>{if(generation===session)leave('Connection lost. Try another room or network.')})}});
peer.on('connection',c=>{if(!host){c.close();return}c.on('open',()=>{if(generation!==session){c.close();return}const slot=roster.findIndex((p,i)=>i>0&&!p);if(state!=='lobby'||slot<0){send(c,{type:'reject',message:slot<0?'This room is full.':'The race has started. Ask the host to create a new room.'});setTimeout(()=>c.close(),300);return}roster[slot]=true;connections.set(slot,c);send(c,{type:'welcome',id:slot,room,roster});broadcast({type:'roster',roster});party();statusLine('Players connected. Ready to race.');let lastSeq=-1;c.on('data',d=>{if(generation!==session||connections.get(slot)!==c)return;if(d?.type==='input'&&d.epoch===epoch&&Number.isSafeInteger(d.seq)&&d.seq>lastSeq&&Number.isFinite(d.x)&&Number.isFinite(d.y)){lastSeq=d.seq;inputs.set(slot,{x:clamp(d.x,-1,1),y:clamp(d.y,-1,1),at:performance.now()})}});c.on('close',()=>{if(generation!==session||connections.get(slot)!==c)return;connections.delete(slot);inputs.delete(slot);roster[slot]=null;broadcast({type:'roster',roster});party();if(state==='lobby')statusLine('A player left.');if(state==='finished')showResult();});c.on('error',()=>c.close())})});}
function snapshot(){return{type:'snapshot',epoch,round,elapsed,state,players,roster,winner:players.winner??null}}
function receiveHost(d){if(!d||typeof d!=='object')return;if(d.type==='reject'){leave(d.message);return}if(d.type==='welcome'){clearTimeout(connectionTimer);localId=d.id;roster=d.roster;party();statusLine('Connected. Waiting for the host to start.');return}if(d.type==='roster'){roster=d.roster;party();return}if(d.type!=='snapshot'||!Array.isArray(d.players)||d.players.length!==4)return;lastSnapshot=performance.now();const fresh=epoch!==d.epoch,previous=state;const old=players;epoch=d.epoch;round=d.round;elapsed=d.elapsed;players=d.players;players.winner=d.winner;roster=d.roster;state=d.state;if(fresh){clearControls();rebuildCourse();stopSounds();$('lobby').classList.add('hidden');$('overlay').classList.add('hidden')}if(old[localId]&&state==='playing'){movementSound(players[localId],Math.hypot(players[localId].x-old[localId].x,players[localId].y-old[localId].y));if(players[localId].energy<old[localId].energy)playEffect('build',.65)}if(state==='finished'&&previous!=='finished'){stopSounds();showResult()}party()}
function startMatch(){if(!isHost||roster.filter(Boolean).length<2)return;epoch++;round=1;reset();players.forEach(p=>p.speed=4.6);clearControls();state='playing';stopSounds();$('lobby').classList.add('hidden');$('overlay').classList.add('hidden');broadcast(snapshot());party()}
// Every occupied slot uses the same movement and shared-lane placement rules.
updatePlayer=function(p,dt){const input=p.id===localId?localInput():inputs.get(p.id);let dx=input?.x||0,dy=input?.y||0;if(p.id!==localId&&(!input||performance.now()-input.at>500))dx=dy=0;const length=Math.hypot(dx,dy);dx/=Math.max(1,length);dy/=Math.max(1,length);const wx=dx*Math.cos(cameraYaw)+dy*Math.sin(cameraYaw),wy=-dx*Math.sin(cameraYaw)+dy*Math.cos(cameraYaw),ox=p.x,oy=p.y,was=p.mode;
if(p.mode==='stairs'){const owner=laneOwner(p),frontier=-(owner.built*.65+.25);if(wy<-.08&&p.y<=frontier+.025){if(owner.built>=stepsNeeded()){p.finished=true;finish(p.id);return}if(p.energy>.001){p.energy=Math.max(0,p.energy-9);owner.built++;if(p.id===localId)playEffect('build',.65)}}if(Math.abs(wy)>.08)p.y=clamp(p.y+Math.sign(wy)*Math.min(1,length)*p.speed*dt,-(owner.built*.65+.25),1.3);p.x=owner.lane;if(p.y>=.55&&p.y>oy)p.mode='gather';
}else if(length>.08){p.x=clamp(p.x+wx*p.speed*dt,-5.7,5.7);p.y=clamp(p.y+wy*p.speed*dt,.1,6.9)}
const traveled=Math.hypot(p.x-ox,p.y-oy);movementSound(p,traveled);if(traveled>.0001){p.dirX=(p.x-ox)/traveled;p.dirY=(p.y-oy)/traveled;p.roll+=traveled*1.5;p.phase+=dt*12}if(was==='gather'&&p.mode==='gather'){p.floorDistance+=traveled;const growth=Math.max(0,p.floorDistance-1.4)-Math.max(0,p.floorDistance-traveled-1.4);p.energy=Math.min(36,p.energy+growth*3.5);const owner=players.reduce((a,b)=>Math.abs(p.x-a.lane)<Math.abs(p.x-b.lane)?a:b);if(p.y<.55&&Math.abs(p.x-owner.lane)<.8&&(p.energy>.001||owner.built>0)){p.activeLane=owner.id;p.mode='stairs'}}};
finish=function(id){if(!isHost||state!=='playing')return;players.winner=id;state='finished';stopSounds();broadcast(snapshot());showResult()};
showResult=function(){const won=players.winner===localId;$('eyebrow').textContent='RACE FINISHED';$('cardTitle').textContent=won?'You win!':`${names[players.winner]} wins!`;$('description').textContent=`${elapsed.toFixed(1)} seconds`;$('steps').classList.add('hidden');$('rankList').textContent='';$('restart').classList.add('hidden');$('record').textContent='';$('start').textContent=isHost?'Race again':'Waiting for host';$('start').disabled=!isHost||roster.filter(Boolean).length<2;$('overlay').classList.remove('hidden')};
togglePause=function(){clearControls();$('lobby').classList.remove('hidden');party();statusLine('The race continues while this panel is open.')};
loop=function(ms){const dt=Math.min((ms-last)/1000,.04);last=ms;if(isHost&&state==='playing'){elapsed+=dt;for(const p of players){if(state!=='playing')break;if(roster[p.id])updatePlayer(p,dt)}}if(ms-netTick>50){netTick=ms;if(isHost&&(state==='playing'||state==='finished'))broadcast(snapshot());else if(hostConn&&state==='playing'){send(hostConn,{type:'input',epoch,seq:seq++,...localInput()});if(performance.now()-lastSnapshot>10000)leave('Connection stalled. Please rejoin a new room.')}}render(ms/1000);requestAnimationFrame(loop)};
$('createRoom').onclick=()=>{const bytes=crypto.getRandomValues(new Uint8Array(8));openRoom(true,Array.from(bytes,n=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[n%31]).join(''))};
$('joinRoom').onclick=()=>{const code=$('joinCode').value.trim().toUpperCase();if(!/^[A-Z0-9]{8}$/.test(code)){statusLine('Enter the 8-character room code.');return}openRoom(false,code)};
$('startMatch').onclick=startMatch;$('start').onclick=startMatch;$('restart').onclick=startMatch;$('leaveRoom').onclick=()=>leave();$('rooms').onclick=togglePause;$('closeRoom').onclick=()=>{$('lobby').classList.add('hidden');clearControls()};
$('copyInvite').onclick=async()=>{try{await navigator.clipboard.writeText($('invite').value);statusLine('Invite link copied.')}catch(e){$('invite').select();statusLine('Select and copy the invitation link.')}};
init3D();reset();state='lobby';party();requestAnimationFrame(loop);
const invited=new URLSearchParams(location.search).get('room');if(invited&&/^[A-Z0-9]{8}$/i.test(invited)){$('joinCode').value=invited;openRoom(false,invited.toUpperCase())}
